language: python
sudo: required
dist: bionic
arch: arm64
env:
  global:

script:
  # Run container in detached state
  - env
deploy:
  - provider: script
    skip_cleanup: true
    script: >  
      bash -cx '
      echo Hello
      env 
      '
    on:
      branch: master
