language: python
sudo: required
dist: bionic
arch: arm64
env:
  global:
    - ARCH=${TRAVIS_ARCH}
    - TAG=${TAG:-latest}
    - DISTRO=centos
    - VERSION=7
    - BRANCH=stein
    - LOGSERVER_PSW=${LOGSERVER_PSW}
    - LOGSERVER=${LOGSERVER}
    - LOGSERVER_PSW=${LOGSERVER_PSW}
    - DOCKER_NAME=${DISTRO}-binary-neutron-openvswitch-agent-${BRANCH}-${ARCH}

script:
  # Run container in detached state
  - sudo apt-get install -y sshpass
  - echo "Hello $DOCKER_NAME ${LOGSERVER_USER}@${LOGSERVER}:/tmp" $(date +%Y%m%d_%H:%m:%s) > /tmp/hello.txt
  - cat /tmp/hello.txt
  - sshpass -p $LOGSERVER_PSW scp /tmp/hello.txt ${LOGSERVER_USER}@${LOGSERVER}:/tmp
  - sudo ufw status
